name: ORG Deployment
on: 
   schedule:
    - cron: '*/5 * * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate XYZ DEVHUB
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Validate source to xyz
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app/main/default -u chand@xyz.com 
      
    - name: Run Test classes
      run: node_modules/sfdx-cli/bin/run force:apex:test:run -l RunLocalTests -d config -u chand@xyz.com -c -r human
  
    - name: Upload Test results
      uses: actions/upload-artifact@v1
      with:
          name: TestResults
          path: TestResults/
          
    - name: Authenticate ABC DEVHUB
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.ABC_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.ABC_DEVHUB_USERNAME}} 
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Validate source to abc
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app/main/default -u chand@abc.com
